### ISSUE TITLE
[discussion] map을 돌 때 key 값으로 crypto.randomUUID()사용

### ISSUE THREAD

**Issue by GreattitJY** [beyondDevelops/AnimalTalk#123]
## 🙋‍♂️ 논의할 사항에 대해 적어주세요~
- map을 돌 때 key 값에 index밖에 넣을 게 없을 경우 브라우저에 내장된 기능인 crypto.randomUUID()를 사용해봐요~!

## 🙋‍♂️ 사전에 계획한 것들과 무엇이 다를까요?
- map을 돌 때 index를 사용하는 것보다 안전해집니다.

## 🙋‍♂️ 제안하실 해결 방안이 있으실까요? 있다면 적어주세요~
- 예시 :
   <img width="423" alt="image" src="https://user-images.githubusercontent.com/103429329/209418139-faeed810-65be-4173-aab5-9cb03e3fd0e2.png">
  <img width="283" alt="image" src="https://user-images.githubusercontent.com/103429329/209418267-fbf922b9-09f1-4d50-88b8-c4501e8d6fb7.png">

- 참고문서 : https://developer.mozilla.org/en-US/docs/Web/API/Crypto

## 🙋‍♂️ 답변
- A의 답변:  
- B의 답변:

## 🙋‍♂️ 결론
-

**Comment by July249** [comment]
오~~ 신박하군요 ㅎㅎ

**Comment by GreattitJY** [comment]
> 오~~ 신박하군요 ㅎㅎ

따로 라이브러리 사용 안 해도 되고 난수화된 암호라 중복에서도 안전한 거 같습니다. 키값을 따로 고민할 필요도 없고요 ㅎㅎ

**Comment by IntHyun** [comment]
오 신기합니다 자주쓰는 방법인가요?

**Comment by GreattitJY** [comment]
> 오 신기합니다 자주쓰는 방법인가요?

저도 코딩정보 공유방에 시우님이 올려준 거 보고 공유한건데요. can i use에서 보니까 global 90%면 많이 쓰이는 거 같아요!
<img width="656" alt="image" src="https://user-images.githubusercontent.com/103429329/209419891-ea1143e4-733b-4710-bbde-45cb1b1fce77.png">

**Comment by July249** [comment]
컴포넌트의 키는 불변해야한다고 하네요. 재렌더링 될때마다 변화하는 경우에는 사용하면 안된다고 합니다.

혹시 crypto.randomUUID()는 불변하지 않게 될까요?

**Comment by GreattitJY** [comment]
이슈 닫겠습니다.
