### ISSUE TITLE
[issue] UserFeed 페이지 로딩중, 게시글 없음 조건부 렌더링 디자인 수정

### ISSUE THREAD

**Issue by July249** [beyondDevelops/AnimalTalk#202]
## 👨‍💻 무엇을 하실 건지 설명해주세요!
- UserFeed 페이지 로딩중, 게시글 없음의 경우 렌더링할 요소 수정

## 🤔 구현방법 및 예상 동작
-

## ⭐ 특이사항
-

**Comment by GreattitJY** [comment]
제가 작업중입니다..!
<img width="502" alt="image" src="https://user-images.githubusercontent.com/103429329/210172811-93a96dc0-69b6-45b6-b49d-17ead100eae3.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/103429329/210172836-68db0762-b942-4dc9-8df9-06cc97ffacd9.png">
로딩 고양이는 깜빡거림 클래스 넣었습니다ㅎ

**Comment by July249** [comment]
확인되었습니다.

해당 이슈는 닫도록 하겠습니다.
