### ISSUE TITLE
[issue] userFeed 렌더링 오류 해결

### ISSUE THREAD

**Issue by GreattitJY** [beyondDevelops/AnimalTalk#239]
## 👨‍💻 무엇을 하실 건지 설명해주세요!
- 프로필 수정 후 유저 피드 렌더링 오류 해결
- 타 유저 프로필에서 내 프로필로 이동 시 렌더링 오류 해결

## 🤔 구현방법 및 예상 동작
- 내 프로필이 정상적으로 렌더링됩니다.

## ⭐ 특이사항
- 없습니다.

**Comment by July249** [comment]
PR 날려주실 때 #174  이슈와 같이 클로즈 이슈에 포함시켜 주시면 좋을 것 같습니다.
