### ISSUE TITLE
[discussion] 색상 정보 관리를 위한 index.css에서 클래스로 관리 여부 의견

### ISSUE THREAD

**Issue by July249** [beyondDevelops/AnimalTalk#26]
색상 정보를 관리의 용이성을 위해 .btn-active, .btn-inactive 등과 같이 ts Boolean에 따른 스타일 관리를 index.css에서 클래스로 진행하는 것이 어떠할까요?

_Originally posted by @July249 in https://github.com/beyondDevelops/AnimalTalk/pull/24#discussion_r1047227315_

**Comment by GreattitJY** [comment]
좋아요. 다음에 추가하겠습니다.

**Comment by GreattitJY** [comment]
적용한 뒤 이슈 닫겠습니다~!

**Comment by GreattitJY** [comment]
적용해서 이슈 닫겠습니다!
