### ISSUE TITLE
[issue] SignUp 페이지 생성

### ISSUE THREAD

**Issue by IntHyun** [beyondDevelops/AnimalTalk#52]
## 👨‍💻 무엇을 하실 건지 설명해주세요!
- 회원가입하는 페이지를 생성할 계획입니다

## 🤔 구현방법 및 예상 동작
- 회원가입 페이지가 따로 있어 만들 예정입니다

## ⭐ 특이사항
- 컴포넌트로 만들어둬서 props만 수정하면 될 것 같습니다.

**Comment by July249** [comment]
@GreattitJY 해당 이슈를 다시 open하신 이유가 궁금합니다! ㅎㅎ
