### ISSUE TITLE
[issue] HeaderBind.jsx header 스타일 수정

### ISSUE THREAD

**Issue by July249** [beyondDevelops/AnimalTalk#65]
## 👨‍💻 무엇을 하실 건지 설명해주세요!
- header 스타일 내 불필요한 스타일 속성을 제거
- height를 강제한 스타일을 제거하여 콘텐츠로 높이 맞춤

## 🤔 구현방법 및 예상 동작
- 중복 또는 불필요한 스타일을 제거하여 디자인의 유지보수성을 향상

## ⭐ 특이사항
-

**Comment by GreattitJY** [comment]
header에 heigth를 주지 않았을 경우 main 때문에 높이가 깨지는 형상이 있어서 준 거로 기억하는데요. 확인 후 빼야 할 거 같습니다!
