### ISSUE TITLE
[issue] Post 컴포넌트에 이미지 캐러셀 구현

### ISSUE THREAD

**Issue by GreattitJY** [beyondDevelops/AnimalTalk#88]
## 👨‍💻 무엇을 하실 건지 설명해주세요!
-  Post 컴포넌트에 이미지 캐러셀을 구현할 생각입니다.

## 🤔 구현방법 및 예상 동작
- 이미지 하단의 버튼 클릭 시 이미지 슬라이드가 작동합니다.

## ⭐ 특이사항
- 없습니다.

**Comment by July249** [comment]
해당 이슈는 구현된 사안입니다.
